apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/demo-app"
        vault.hashicorp.com/role: "demo-app"
    spec:
      serviceAccountName: demo-app
      containers:
      - name: demo-app
        image: sebica20033/demo-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: default
